---
version: "3.2"

services:
  db:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=sonar # change me
      - POSTGRES_PASSWORD=mypass# change me
      - POSTGRES_DB=sonarqube
    networks:
      - traefik_proxy
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:7.7-community
    environment:
      - sonar.jdbc.username=sonar # change me
      - sonar.jdbc.password=mypass # change me
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
    networks:
      - traefik_proxy
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_bundled-plugins:/opt/sonarqube/bundled-plugins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`DNS`)" # DNS change me
      - "traefik.http.routers.sonarqube.entrypoints=websecure"

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
  sonarqube_logs:
networks:
  traefik_proxy:
    name: traefik_proxy
