version: '3.2'

volumes:
  traefik-ssl-certs:
    driver: local
networks:
  traefik_proxy:
    name: traefik_proxy

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/traefik:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik/:/var/log/traefik/:rw
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik1.wolverine.cefim-formation.org`)
      - traefik.http.routers.traefik.service=api@internal
